### PR TITLE
[HP-141] Give ClosedPOD Child Page Tables A Fixed  Table-Layout

### PR DESCRIPTION
**Pull request by dchukhin**
https://caktus.atlassian.net/browse/HP-141

ClosedPOD child page tables now use a new CSS class to set the table-layout to be fixed.

### CODE REVIEW

**Review by vkurup — APPROVED** [review]
This works. Wonder if you could apply similar changes to the reports page and the recently updated table to address Kat's concern: https://caktusgroup.slack.com/archives/C01J4MFMH9S/p1617660638229800

(If not, let's merge this and fix that separately)

**Review by Audiosutras — APPROVED** [review]
🚀

**Comment by Audiosutras** [comment]
> This works. Wonder if you could apply similar changes to the reports page and the recently updated table to address Kat's concern: https://caktusgroup.slack.com/archives/C01J4MFMH9S/p1617660638229800
> 
> (If not, let's merge this and fix that separately)

Please ignore my approval.

**Comment by dchukhin** [comment]
Closing in favor of #133

**Pull request closed without merging**
