### PR TITLE
[DIS-1701] Part II: Add Button Snippet To Rich Text Sections

### PR DESCRIPTION
**Pull request by dchukhin**
https://caktus.atlassian.net/browse/DIS-1701

This pull request makes it possible for Wagtail users to add a button at the end of a rich text area by choosing a `ButtonSnippet`, which requires a button text and a relative URL.

### CODE REVIEW

**Comment by Audiosutras** [comment]
AFter #191 is merged, can you merge develop?

**Comment by dchukhin** [comment]
Sure, that pull request has been merged, and I've merged the `develop` branch into this branch

**Comment by Audiosutras** [comment]
Thanks, should we add a migration with the suggested button text and relative url for the forms that we are currently managing?

**Review by Audiosutras — APPROVED** [review]
💯

**Pull request merged**
