### PR TITLE
Update To Latest Django Bugfix Version

### PR DESCRIPTION
**Pull request by dchukhin**
This pull request upgrades Django to the latest bugfix version for Django3.2.

### CODE REVIEW

**Review by ronardcaktus — APPROVED** [review]
Looks 🦊

Mr. 🥋I thought it would be a good idea to only notify users of LTS releases on the Wagtail admin. If you disagree, feel free to remove it.

**Comment by dchukhin** [comment]
That sounds great; it looks like there's a new bugfix release of Django 3.2, so we should update to it too

**Comment by ronardcaktus** [comment]
> That sounds great; it looks like there's a new bugfix release of Django 3.2, so we should update to it too

I updated it to the latest.

**Comment by dchukhin** [comment]
Thanks for making the change @ronardcaktus 🍄

**Pull request merged**
